### ISSUE TITLE
Options for Sharing Publicly

### ISSUE THREAD

**Issue by jenningsanderson** [jenningsanderson/overture-daylight-mvp#1]
How do we put _this map_ on the OMF website?

My Suggestion:

1. Transfer this repository to OvertureMaps 
2. Point `labs.overturemaps.org` or something similar to Github.  Then, this map would be available at: `labs.overturemaps.org/overture-daylight/`, 
3. Create `iframe` on the overture maps website with this map.

In this way, there remains only one, open repository that has the instructions and code to run this webpage.

**Comment by jonahadkins** [comment]
+1 🚀
